#!/bin/sh 

[ "$INTERFACE" = "wan" ] && {

	[ $(uci -q get ffwizard.vpn.enabled) -eq 1 ] || return

	case "$ACTION" in 
		ifup) 
			/etc/init.d/fastd start
		;;
		ifdown)
			/etc/init.d/fastd stop
			/etc/init.d/fastd disable
		;;
	esac
}

# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
