#!/bin/sh
# shellcheck disable=SC2154

. /lib/functions.sh

dev=$1

[ -n "$dev" ] || {
	exit 1
}

ip route del default table 50
ip rule del to 10.0.0.0/8 prio 30001 table main
ip rule del from 10.63.0.0/16 prio 30010 table 50
ip rule del to 100.64.0.1/10 prio 30002 table main
ip rule del from 100.64.0.1/10 prio 30003 table 50

/sbin/ip link set dev "$dev" down

ifdown fastd


exit 0
# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
