#!/bin/sh
# shellcheck disable=SC2154

. /lib/functions.sh

dev=$1
remote=$2

[ -n "$dev" ] || {
	exit 1
}

json="$(uclient-fetch -q -T 4 -O- "http://$remote/freifunk/vpn")"
json_load "$json" 2>/dev/null
json_get_var gateway_ip gateway_ip
json_cleanup

ip route del default via $gateway_ip table 50
ip rule del to 10.0.0.0/8 prio 30001 table main
ip rule del from 10.63.0.0/16 prio 30010 table 50
ip rule del to 100.64.0.1/10 prio 30002 table main
ip rule del from 100.64.0.1/10 prio 30003 table 50

/sbin/ip link set dev "$dev" down


exit 0
# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
